# Generated by Django 3.2.4 on 2021-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='blog_app/images')),
                ('country', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('short_discription', models.TextField()),
                ('discription', models.TextField()),
            ],
        ),
    ]
