# Generated by Django 3.2.4 on 2021-06-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0005_blog_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_app/images'),
            preserve_default=False,
        ),
    ]
